# Site settings
title: "Thierno Oumar DIALLO"
logo: "logo.png"
profile: "administrator.png"
email: /f/mayvpeqd
url: https://tod01.github.io
description: "I am a big data enthusiast. I am interested in all areas of data science (Machine Learning, Data Mining, Data Engineering,...)."
keywords: "Thierno Oumar Diallo, tod01, tod, Data Engineer, Ingénieur de données, Data Scientist, NLP, Machine Learning, MLOps"
skills: "Data Engineer - Data Scientist - MLOps Engineer - Machine Learning Engineer"
meta_author: Thierno Oumar DIALLO

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Thierno Oumar Diallo
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: "twitter"
    url: "http://twitter.com/umartod"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/tod01/"
  - title: "stack-overflow"
    url: "https://stackoverflow.com/users/13159727/tod01"
  - title: "github"
    url: "http://github.com/tod01"

# more about page
more_about:
  - logo: "../"

# Postal address (add as many lines as necessary)
address:
  - line: 78140 Velizy Villacoublay, France
  #- line: 78140 Velizy Villacoublay, France

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
